# Generated by Django 5.2.6 on 2025-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('status', models.CharField(choices=[('to_watch', 'To watch'), ('watched', 'Watched')])),
            ],
        ),
    ]
